export const GET_BUOY_REQUEST = "GET_BUOY_REQUEST";
export const GET_BUOY_SUCCESS = "GET_BUOY_SUCCESS";
export const GET_BUOY_FAILURE = "GET_BUOY_FAILURE";

export const CREATE_BUOY_REQUEST = "CREATE_BUOY_REQUEST";
export const CREATE_BUOY_SUCCESS = "CREATE_BUOY_SUCCESS";
export const CREATE_BUOY_FAILURE = "CREATE_BUOY_FAILURE";

export const UPDATE_BUOY_REQUEST = "UPDATE_BUOY_REQUEST";
export const UPDATE_BUOY_SUCCESS = "UPDATE_BUOY_SUCCESS";
export const UPDATE_BUOY_FAILURE = "UPDATE_BUOY_FAILURE";

export const DELETE_BUOY_REQUEST = "DELETE_BUOY_REQUEST";
export const DELETE_BUOY_SUCCESS = "DELETE_BUOY_SUCCESS";
export const DELETE_BUOY_FAILURE = "DELETE_BUOY_FAILURE";

export const LIST_BUOYS_REQUEST = "LIST_BUOYS_REQUEST";
export const LIST_BUOYS_SUCCESS = "LIST_BUOYS_SUCCESS";
export const LIST_BUOYS_FAILURE = "LIST_BUOYS_FAILURE";
