export const GET_RESERVATION_REQUEST = "GET_RESERVATIONS_REQUEST";
export const GET_RESERVATION_SUCCESS = "GET_RESERVATIONS_SUCCESS";
export const GET_RESERVATION_FAILURE = "GET_RESERVATIONS_FAILURE";

export const DELETE_RESERVATION_REQUEST = "DELETE_RESERVATION_REQUEST";
export const DELETE_RESERVATION_SUCCESS = "DELETE_RESERVATION_SUCCESS";
export const DELETE_RESERVATION_FAILURE = "DELETE_RESERVATION_FAILURE";

export const CREATE_RESERVATION_REQUEST = "CREATE_RESERVATION_REQUEST";
export const CREATE_RESERVATION_SUCCESS = "CREATE_RESERVATION_SUCCESS";
export const CREATE_RESERVATION_FAILURE = "CREATE_RESERVATION_FAILURE";

export const UPDATE_RESERVATION_REQUEST = "UPDATE_RESERVATION_REQUEST";
export const UPDATE_RESERVATION_SUCCESS = "UPDATE_RESERVATION_SUCCESS";
export const UPDATE_RESERVATION_FAILURE = "UPDATE_RESERVATION_FAILURE";
