export const GET_SHIP_REQUEST = "GET_SHIP_REQUEST";
export const GET_SHIP_SUCCESS = "GET_SHIP_SUCCESS";
export const GET_SHIP_FAILURE = "GET_SHIP_FAILURE";

export const CREATE_SHIP_REQUEST = "CREATE_SHIP_REQUEST";
export const CREATE_SHIP_SUCCESS = "CREATE_SHIP_SUCCESS";
export const CREATE_SHIP_FAILURE = "CREATE_SHIP_FAILURE";

export const UPDATE_SHIP_REQUEST = "UPDATE_SHIP_REQUEST";
export const UPDATE_SHIP_SUCCESS = "UPDATE_SHIP_SUCCESS";
export const UPDATE_SHIP_FAILURE = "UPDATE_SHIP_FAILURE";

export const DELETE_SHIP_REQUEST = "DELETE_SHIP_REQUEST";
export const DELETE_SHIP_SUCCESS = "DELETE_SHIP_SUCCESS";
export const DELETE_SHIP_FAILURE = "DELETE_SHIP_FAILURE";
